# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install Python dependencies from requirements.txt
# Ensure it includes selenium
RUN pip install --no-cache-dir -r requirements2.txt

# Install system dependencies required for Firefox and GeckoDriver
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    firefox-esr \
    && rm -rf /var/lib/apt/lists/*

# Install GeckoDriver (strip "v" from version for filename)
RUN GECKODRIVER_TAG=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4) && \
    GECKODRIVER_VERSION=$(echo $GECKODRIVER_TAG | sed 's/^v//') && \
    echo "Installing GeckoDriver version $GECKODRIVER_TAG..." && \
    wget -O /tmp/geckodriver.tar.gz "https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_TAG/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz" && \
    tar -xzf /tmp/geckodriver.tar.gz -C /usr/local/bin && \
    rm /tmp/geckodriver.tar.gz && \
    chmod +x /usr/local/bin/geckodriver


# Set display port to avoid crash
ENV DISPLAY=:99

# Command to run on container start
CMD ["python", "./test_html_elements.py"]
