from selenium import webdriver
from selenium.webdriver.firefox.options import Options
import unittest
import sqlite3

class TestTaskData(unittest.TestCase):
    def setUp(self):
        # Setup Firefox options
        firefox_options = Options()
        firefox_options.add_argument("--headless")  # Ensures the browser window does not open
        firefox_options.add_argument("--no-sandbox")
        firefox_options.add_argument("--disable-dev-shm-usage")
        self.driver = webdriver.Firefox(options=firefox_options)

        # Connect to the SQLite database used by Flask
        self.db = sqlite3.connect("/nfs/demo.db")  # Make sure this path matches the actual one used in Flask

    def test_task_data(self):
        driver = self.driver
        driver.get("http://10.48.10.107")  # Replace with your target website
        
        # Query the database for the test data generated by the data-gen script
        cursor = self.db.cursor()
        cursor.execute("SELECT name FROM tasks WHERE name LIKE 'Test Task %'")  # Adjust to match the pattern from data-gen.py
        test_tasks = cursor.fetchall()

        # Check that each test task exists on the page
        for task in test_tasks:
            test_name = task[0]
            self.assertIn(test_name, driver.page_source, f"Test task {test_name} not found in page source")

        print("Test completed successfully. All test tasks were verified.")

    def tearDown(self):
        # Close the browser and the database connection
        self.driver.quit()
        self.db.close()

if __name__ == "__main__":
    unittest.main()

