from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options
import unittest
import sqlite3

class TestContacts(unittest.TestCase):
    def setUp(self):
        # Setup Firefox options
        firefox_options = Options()
        firefox_options.add_argument("--headless")  # Ensures the browser window does not open
        firefox_options.add_argument("--no-sandbox")
        firefox_options.add_argument("--disable-dev-shm-usage")
        self.driver = webdriver.Firefox(options=firefox_options)

        # Connect to the SQLite database used by Flask
        self.db = sqlite3.connect("/nfs/demo.db")  # Make sure this path matches the actual one used in Flask

    def test_contacts(self):
        driver = self.driver
        driver.get("http://10.48.10.107")  # Replace with your target website
        
        # Wait for the page to load
        # You can add a wait here if the page takes time to load

        # Query the database for the test contacts generated by the data-gen script
        cursor = self.db.cursor()
        cursor.execute("SELECT name FROM contacts WHERE name LIKE 'Test Name %'")
        test_contacts = cursor.fetchall()

        # Check that each test contact exists on the page
        for contact in test_contacts:
            test_name = contact[0]
            self.assertIn(test_name, driver.page_source, f"Test contact {test_name} not found in page source")

        print("Test completed successfully. All test contacts were verified.")

    def tearDown(self):
        # Close the browser and the database connection
        self.driver.quit()
        self.db.close()

if __name__ == "__main__":
    unittest.main()
